services:
  product-db:
    image: postgres:16-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    ports:
      - "5991:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  product-db-data:
